apiVersion: v1
kind: Pod
metadata:
  name: labelpod
  namespace: learn
  labels:
    environment: staging
    tier: frontend
spec:
  containers:
  - name: labelcontainer
    image: nginx
    ports:
    - containerPort: 80
  restartPolicy: Never
