apiVersion: v1
kind: Pod
metadata:
  name: annotationspod
  namespace: learn
  annotations:
    k8slink: "https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/"
spec:
  containers:
  - name: annotationscontainer
    image: nginx
    ports:
    - containerPort: 80
  restartPolicy: Never
